// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace VapeShopWebSite.Migrations
{
    [DbContext(typeof(EF_DataContext))]
    partial class EF_DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("VapeShopWebSite.Models.LiquidsModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("id"));

                    b.Property<int>("amount_of_salt")
                        .HasColumnType("integer");

                    b.Property<string>("brand")
                        .HasColumnType("text");

                    b.Property<string>("flavor")
                        .HasColumnType("text");

                    b.Property<string>("img1_src")
                        .HasColumnType("text");

                    b.Property<string>("line")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pgvg")
                        .HasColumnType("text");

                    b.Property<int>("price")
                        .HasColumnType("integer");

                    b.Property<int>("volume")
                        .HasColumnType("integer");

                    b.Property<string>("whatnic")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("liquids");
                });
#pragma warning restore 612, 618
        }
    }
}
